http://example.org/baseURL: "veronicayaxinlyu.netlify.app/"
languageCode: en-us
title: Portfolio website for Yaxin Lyu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Yaxin Lyu. I'm a mfa candidate from the London Business School.
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 9 Churchyard Row
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ylyu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (044) 07421239566
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: YAXIN LYU
    enable: yes
    quicklinks:
      #- alt: HTML5 UP
        #text: 'Design: '
        #url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
       # label: Facebook
       # url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/ver_lyuyx/
      - icon: fa-github
        label: GitHub
        url: https://github.com/YAXINLYU
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.cn/in/yaxinlyu9912/
  image: 'yaxinlyu.JPG'
  name: Yaxin Lyu
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
   # links:
     # - name: Home
      #  url: '#'
      #- name: Blogs
     #   url: blogs
     # - name: Generic Blog
      #  url: blogs/ipsum
     # - name: Elements
       # url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    #title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Veronica.JPG
        #subtitle: 
        title: CV
        url: blogs/CV.jpg
      - image: Bakery.JPG
        subtitle: Part time baker
        title: My Hobbies!
        url: blogs/Bakery.JPG
      - image: pic03.jpg
        #subtitle: Lorem Etiam Nullam
        title: Analysis on Drinks, IMDB, Financial Stocks, Inflation Transitory and German Elections
        url: blogs/Spirits_IMDB_Stocks_Inflation_German_Election.html
      - image: Pets.jpg
        subtitle: Tangtang and Erbao
        title: Pets of Mine
        url: blogs/Pets.jpg
      - image: pic05.jpg
        #subtitle: Ipsum Dolor Sit Amet
        title: Analysis on Climate Change, GSS, Biden's Approval Margins, Tfl Bike Sharing and Changes in CPI
        url: blogs/homework2.html
      - image: pic06.jpg
        #subtitle: Feugiat Amet Tempus
        title: Analyis on Youth Risk Behavior Surveillance, IMDB Rating, Pay Discrimination, Yield Curve Inversion and GDP Components
        url: blogs/Homework3_Group_B12.html
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
